name: Infra setup
description: Setup infra using Pulumi
outputs:
  webGitUrl:
    description: 'Web Git URL'
    value: ${{ steps.webGitUrl.outputs.url }}
runs:
  using: composite
  steps:
    - id: webGitUrl
      run: echo "::set-output name=url::https://google.com"
      shell: bash
    