name: Dotnet Action
description: Build, Test, Deploy dotnet
runs:
  using: "composite"
  steps:
    - run: echo Dotnet Action
      shell: bash
    - run: echo Clone project
      shell: bash
    - run: echo Build project
      shell: bash
    - run: echo Test project
      shell: bash
    - run: echo Deploy project
      shell: bash