name: Continous Delivery Workflow

on:
  workflow_run:
    workflows: ['Setup Infra']
    types:
      - completed
  push:
    paths:
      - 'dotnet/*'

jobs:
  infra:
    runs-on: ubuntu-latest
    outputs:
      webGitUrl: ${{ steps.setup-infra.outputs.webGitUrl }}
    steps:
      - uses: actions/checkout@v2
      - id: setup-infra
        uses: ./infra

  dotnet:
    runs-on: windows-latest
    needs: infra
    steps:
      - uses: actions/checkout@v2
      - uses: ./dotnet
        with:
          webGitUrl: ${{ needs.infra.outputs.webGitUrl }}