name: Setup Infra

on:
  workflow_dispatch:
    inputs:
      environments:
        description: Enter comma separated envs which needs to be created (e.g. dev,qc,stg)
        required: true

jobs:

  create_or_update_infra:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ github.event.inputs.environments }}
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'INFRA_SECRET'
          value: 'some value'
          repository: honey-ramgarhia/ga-playground
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

